// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

export interface AppEmote {
    "id": string;
    "name": string;
    "lightSrcSet": string;
    "darkSrcSet": string;
    "provider": string;
    "section": string;
    "zeroWidth": boolean;
    "emoteStack": (AppEmote | null)[] | null;
}

export type AppEmoteMap = { [_ in string]?: AppEmote | null } | null;

export interface AppEmoteSet {
    "Id": string;
    "Provider": string;
    "Section": string;
    "Emotes": AppEmoteMap;
}

export interface AppUser {
    "id": string;
    "login": string;
    "display_name": string;
    "type": string;
    "broadcaster_type": string;
    "description": string;
    "profile_image_url": string;
    "offline_image_url": string;
    "view_count": number;
    "email": string;
    "created_at": time$0.Time;
    "access_token": string;
}

export type EmptyEvent = any;

export interface NewEmoteSetEvent {
    "BroadcasterId": string;
    "ChannelSpecific": boolean;
    "Id": string;
    "Provider": string;
    "Section": string;
    "Emotes": AppEmoteMap;
}

export interface SwitchTabNextEvent {
    "Forward": boolean;
}
