// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as eventsub$0 from "../../../../../chatter-wails/services/eventsub/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as types$0 from "../../../../../chatter-wails/shared/types/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "gel:ban": eventsub$0.BanEventData;
            "gel:chat-message": eventsub$0.ESChatMessage | null;
            "gel:chat-open": eventsub$0.ChatOpenData;
            "gel:clear-msg": eventsub$0.ClearMsgEventData;
            "gel:emote:new-set": types$0.NewEmoteSetEvent;
            "gel:shared-chat-begin": eventsub$0.SharedChatBeginEventData;
            "gel:shared-chat-end": eventsub$0.SharedChatEndEventData;
            "gel:shared-chat-update": eventsub$0.SharedChatUpdateEventData;
            "gel:stream-data": eventsub$0.StreamData;
            "gel:user-login": types$0.AppUser | null;
        }
    }
}
